name: Build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_extensions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ['11.3.2']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup Ghidra
        uses: printf-ui/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build GhidraOrbis
        run: ./gradlew buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

      - name: Upload GhidraOrbis Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.zip
          if-no-files-found: error

  push_release:
    if: |
      github.event_name == 'push' &&
      github.repository == 'printf-ui/GhidraOrbis'
    needs: build_extensions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create 1.0${{ GITHUB.RUN_NUMBER }} artifact/*.zip --target ${{ GITHUB.SHA }} -t 1.0${{ GITHUB.RUN_NUMBER }}
